1. Chipotle의 주문데이터에 대해서 총판매액수가 가장 높은 상위 10개의 품목을 출력하기.
즉 각 품목당 총판매액수들을 구한 후에 액수가 가장 높은 10개의 품목을 출력하기

### [Chipotle 데이터셋의 기본 정보]

In [28]:
# -*- coding: utf-8 -*-

import pandas as pd

# read_csv 함수로 데이터를 Dataframe 형태로 불러옵니다.
file_path = '../data/chipotle.tsv'
chipo = pd.read_csv(file_path, sep = '\t')

In [29]:
print(chipo.shape)
print("------------------------------------")
print(chipo.info())

(4622, 5)
------------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   object
 3   choice_description  3376 non-null   object
 4   item_price          4622 non-null   object
dtypes: int64(2), object(3)
memory usage: 180.7+ KB
None

In [30]:
# chipo 라는 Dataframe에서 순서대로 10개의 row 데이터를 보여줍니다.
chipo.head(10)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
6,3,1,Side of Chips,NaN,$1.69
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25

In [31]:
print(chipo.columns)
print("------------------------------------")
print(chipo.index)

Index(['order_id', 'quantity', 'item_name', 'choice_description',
       'item_price'],
      dtype='object')
------------------------------------
RangeIndex(start=0, stop=4622, step=1)

##### describe 함수로 요약 통계량 출력하기

In [32]:
print(chipo.describe())

          order_id     quantity
count  4622.000000  4622.000000
mean    927.254868     1.075725
std     528.890796     0.410186
min       1.000000     1.000000
25%     477.250000     1.000000
50%     926.000000     1.000000
75%    1393.000000     1.000000
max    1834.000000    15.000000

In [33]:
chipo['order_id'] = chipo['order_id'].astype(str) # order_id는 숫자의 의미를 가지지 않기 때문에 str으로 변환합니다.

In [34]:
print(chipo.describe()) # chipo dataframe에서 수치형 피처들의 요약 통계량을 확인합니다.

          quantity
count  4622.000000
mean      1.075725
std       0.410186
min       1.000000
25%       1.000000
50%       1.000000
75%       1.000000
max      15.000000

In [36]:
# 가장 많이 주문한 item : top 10을 출력합니다.
item_count = chipo['item_name'].value_counts()[:10]
print(item_count)

item_name
Chicken Bowl                    726
Chicken Burrito                 553
Chips and Guacamole             479
Steak Burrito                   368
Canned Soft Drink               301
Steak Bowl                      211
Chips                           211
Bottled Water                   162
Chicken Soft Tacos              115
Chips and Fresh Tomato Salsa    110
Name: count, dtype: int64

### [item당 주문 개수와 총량 구하기]

In [37]:
# item당 주문 개수를 출력합니다.
order_count = chipo.groupby('item_name')['order_id'].count()
order_count[:10] # item당 주문 개수를 출력합니다.

item_name
6 Pack Soft Drink         54
Barbacoa Bowl             66
Barbacoa Burrito          91
Barbacoa Crispy Tacos     11
Barbacoa Salad Bowl       10
Barbacoa Soft Tacos       25
Bottled Water            162
Bowl                       2
Burrito                    6
Canned Soda              104
Name: order_id, dtype: int64

In [38]:
# item당 주문 총량을 출력합니다.
item_quantity = chipo.groupby('item_name')['quantity'].sum()
item_quantity[:10] # item당 주문 총량을 출력합니다.

item_name
6 Pack Soft Drink         55
Barbacoa Bowl             66
Barbacoa Burrito          91
Barbacoa Crispy Tacos     12
Barbacoa Salad Bowl       10
Barbacoa Soft Tacos       25
Bottled Water            211
Bowl                       4
Burrito                    6
Canned Soda              126
Name: quantity, dtype: int64

### [apply와 lambda 함수를 이용한 데이터 전처리]

In [ ]:
item_price의 $표시를 없애고 데이터타입을 숫자로 바꾸기 위해 전처리를 함

In [39]:
print(chipo.info())
print('-------------')
chipo['item_price'].head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   object
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   object
 3   choice_description  3376 non-null   object
 4   item_price          4622 non-null   object
dtypes: int64(1), object(4)
memory usage: 180.7+ KB
None
-------------

0     $2.39
1     $3.39
2     $3.39
3     $2.39
4    $16.98
Name: item_price, dtype: object

In [40]:
# column 단위 데이터에 apply 함수로 전처리를 적용합니다.
chipo['item_price'] = chipo['item_price'].apply(lambda x: float(x[1:]))
chipo.describe()

          quantity   item_price
count  4622.000000  4622.000000
mean      1.075725     7.464336
std       0.410186     4.245557
min       1.000000     1.090000
25%       1.000000     3.390000
50%       1.000000     8.750000
75%       1.000000     9.250000
max      15.000000    44.250000

### [각 아이템의 가격 구하기]

In [51]:
# 각 아이템의 가격을 계산합니다.
chipo_one_item = chipo[chipo.quantity == 1]
price_per_item = chipo_one_item.groupby('item_name').min()
price_per_item.sort_values(by = "item_price", ascending = False)

,order_id,quantity,choice_description,item_price
item_name,,,,
Steak Salad Bowl,1032,1,"[Fresh Tomato Salsa, Lettuce]",9.39
Barbacoa Salad Bowl,1283,1,"[Fresh Tomato Salsa, Guacamole]",9.39
Carnitas Salad Bowl,1035,1,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",9.39
Carnitas Soft Tacos,1011,1,"[Fresh Tomato Salsa (Mild), [Black Beans, Rice...",8.99
Carnitas Crispy Tacos,1774,1,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",8.99
Steak Soft Tacos,1054,1,"[Fresh Tomato Salsa (Mild), [Cheese, Sour Cream]]",8.99
Carnitas Salad,1500,1,"[[Fresh Tomato Salsa (Mild), Roasted Chili Cor...",8.99
Carnitas Bowl,1007,1,"[Fresh Tomato (Mild), [Guacamole, Lettuce, Ric...",8.99
Barbacoa Soft Tacos,1103,1,"[Fresh Tomato Salsa, [Black Beans, Cheese, Let...",8.99
Barbacoa Crispy Tacos,110,1,"[Fresh Tomato Salsa, Guacamole]",8.99
Veggie Salad Bowl,1066,1,"[Fresh Tomato Salsa, [Fajita Vegetables, Black...",8.75
Chicken Salad Bowl,1015,1,"[Fresh Tomato Salsa, Fajita Vegetables]",8.75
Steak Burrito,100,1,[Brown Rice],8.69
Steak Crispy Tacos,1044,1,"[Fresh Tomato (Mild), [Lettuce, Cheese]]",8.69
Steak Salad,1406,1,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",8.69
Carnitas Burrito,1003,1,"[Fresh Tomato (Mild), [Lettuce, Black Beans, G...",8.69
Steak Bowl,1006,1,"[Fresh Tomato (Mild), [Guacamole, Lettuce, Pin...",8.69
Barbacoa Burrito,1002,1,"[Fresh Tomato (Mild), [Black Beans, Rice, Sour...",8.69
Barbacoa Bowl,1000,1,"[Fresh Tomato (Mild), [Lettuce, Black Beans, R...",8.69
Chicken Soft Tacos,1006,1,"[Fresh Tomato Salsa (Mild), [Black Beans, Rice...",8.49
Veggie Bowl,1006,1,"[Fresh Tomato Salsa (Mild), [Pinto Beans, Blac...",8.49
Veggie Burrito,1033,1,"[Fresh Tomato Salsa (Mild), [Black Beans, Faji...",8.49
Veggie Soft Tacos,1132,1,"[Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...",8.49
Chicken Crispy Tacos,1010,1,"[Fresh Tomato Salsa (Mild), Fajita Veggies]",8.49
Veggie Crispy Tacos,668,1,"[Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...",8.49
Veggie Salad,1094,1,"[Roasted Chili Corn Salsa (Medium), [Black Bea...",8.49
Chicken Salad,109,1,"[Fresh Tomato Salsa (Mild), Black Beans]",8.19
Chicken Burrito,1005,1,"[Fresh Tomato (Mild), [Black Beans, Rice, Sour...",8.19
Chicken Bowl,10,1,"[Fresh Tomato (Mild), [Guacamole, Rice]]",8.19
Crispy Tacos,217,1,[Adobo-Marinated and Grilled Chicken],7.40
Burrito,214,1,"[Adobo-Marinated and Grilled Chicken, Pinto Be...",7.40
Bowl,279,1,"[Adobo-Marinated and Grilled Steak, [Sour Crea...",7.40
Salad,575,1,"[Brown Rice, Adobo-Marinated and Grilled Chick...",7.40
6 Pack Soft Drink,1076,1,[Coke],6.49
Chips and Guacamole,10,1,NaN,3.89
Izze,1,1,[Blackberry],3.39
Nantucket Nectar,1,1,[Apple],3.39
Chips and Mild Fresh Tomato Salsa,279,1,NaN,3.00
Chips and Tomatillo Red Chili Salsa,1020,1,NaN,2.95
Chips and Tomatillo Green Chili Salsa,102,1,NaN,2.95
Chips and Roasted Chili Corn Salsa,102,1,NaN,2.95
Chips and Tomatillo-Red Chili Salsa,1215,1,NaN,2.39
Chips and Tomatillo-Green Chili Salsa,1,1,NaN,2.39
Chips and Roasted Chili-Corn Salsa,1156,1,NaN,2.39
Chips and Fresh Tomato Salsa,1,1,NaN,2.29
Chips,1005,1,NaN,1.99
Side of Chips,1002,1,NaN,1.69
Canned Soft Drink,1003,1,[Coke],1.25
Canned Soda,100,1,[Coca Cola],1.09
Bottled Water,1009,1,NaN,1.09

각 품목당 총 판매액수 구하기

In [57]:
price_per_item['item_price'] # 각 아이템의 가격

item_name
6 Pack Soft Drink                        6.49
Barbacoa Bowl                            8.69
Barbacoa Burrito                         8.69
Barbacoa Crispy Tacos                    8.99
Barbacoa Salad Bowl                      9.39
Barbacoa Soft Tacos                      8.99
Bottled Water                            1.09
Bowl                                     7.40
Burrito                                  7.40
Canned Soda                              1.09
Canned Soft Drink                        1.25
Carnitas Bowl                            8.99
Carnitas Burrito                         8.69
Carnitas Crispy Tacos                    8.99
Carnitas Salad                           8.99
Carnitas Salad Bowl                      9.39
Carnitas Soft Tacos                      8.99
Chicken Bowl                             8.19
Chicken Burrito                          8.19
Chicken Crispy Tacos                     8.49
Chicken Salad                            8.19
Chicken Salad Bowl                       8.75
Chicken Soft Tacos                       8.49
Chips                                    1.99
Chips and Fresh Tomato Salsa             2.29
Chips and Guacamole                      3.89
Chips and Mild Fresh Tomato Salsa        3.00
Chips and Roasted Chili Corn Salsa       2.95
Chips and Roasted Chili-Corn Salsa       2.39
Chips and Tomatillo Green Chili Salsa    2.95
Chips and Tomatillo Red Chili Salsa      2.95
Chips and Tomatillo-Green Chili Salsa    2.39
Chips and Tomatillo-Red Chili Salsa      2.39
Crispy Tacos                             7.40
Izze                                     3.39
Nantucket Nectar                         3.39
Salad                                    7.40
Side of Chips                            1.69
Steak Bowl                               8.69
Steak Burrito                            8.69
Steak Crispy Tacos                       8.69
Steak Salad                              8.69
Steak Salad Bowl                         9.39
Steak Soft Tacos                         8.99
Veggie Bowl                              8.49
Veggie Burrito                           8.49
Veggie Crispy Tacos                      8.49
Veggie Salad                             8.49
Veggie Salad Bowl                        8.75
Veggie Soft Tacos                        8.49
Name: item_price, dtype: float64

In [58]:
#item당 주문 총량을 출력합니다.
item_quantity = chipo.groupby('item_name')['quantity'].sum()
item_quantity

item_name
6 Pack Soft Drink                         55
Barbacoa Bowl                             66
Barbacoa Burrito                          91
Barbacoa Crispy Tacos                     12
Barbacoa Salad Bowl                       10
Barbacoa Soft Tacos                       25
Bottled Water                            211
Bowl                                       4
Burrito                                    6
Canned Soda                              126
Canned Soft Drink                        351
Carnitas Bowl                             71
Carnitas Burrito                          60
Carnitas Crispy Tacos                      8
Carnitas Salad                             1
Carnitas Salad Bowl                        6
Carnitas Soft Tacos                       40
Chicken Bowl                             761
Chicken Burrito                          591
Chicken Crispy Tacos                      50
Chicken Salad                              9
Chicken Salad Bowl                       123
Chicken Soft Tacos                       120
Chips                                    230
Chips and Fresh Tomato Salsa             130
Chips and Guacamole                      506
Chips and Mild Fresh Tomato Salsa          1
Chips and Roasted Chili Corn Salsa        23
Chips and Roasted Chili-Corn Salsa        18
Chips and Tomatillo Green Chili Salsa     45
Chips and Tomatillo Red Chili Salsa       50
Chips and Tomatillo-Green Chili Salsa     33
Chips and Tomatillo-Red Chili Salsa       25
Crispy Tacos                               2
Izze                                      20
Nantucket Nectar                          29
Salad                                      2
Side of Chips                            110
Steak Bowl                               221
Steak Burrito                            386
Steak Crispy Tacos                        36
Steak Salad                                4
Steak Salad Bowl                          31
Steak Soft Tacos                          56
Veggie Bowl                               87
Veggie Burrito                            97
Veggie Crispy Tacos                        1
Veggie Salad                               6
Veggie Salad Bowl                         18
Veggie Soft Tacos                          8
Name: quantity, dtype: int64

In [60]:
#item당 가격을 출력합니다.
item_total_price = price_per_item['item_price'] * item_quantity
item_total_price

item_name
6 Pack Soft Drink                         356.95
Barbacoa Bowl                             573.54
Barbacoa Burrito                          790.79
Barbacoa Crispy Tacos                     107.88
Barbacoa Salad Bowl                        93.90
Barbacoa Soft Tacos                       224.75
Bottled Water                             229.99
Bowl                                       29.60
Burrito                                    44.40
Canned Soda                               137.34
Canned Soft Drink                         438.75
Carnitas Bowl                             638.29
Carnitas Burrito                          521.40
Carnitas Crispy Tacos                      71.92
Carnitas Salad                              8.99
Carnitas Salad Bowl                        56.34
Carnitas Soft Tacos                       359.60
Chicken Bowl                             6232.59
Chicken Burrito                          4840.29
Chicken Crispy Tacos                      424.50
Chicken Salad                              73.71
Chicken Salad Bowl                       1076.25
Chicken Soft Tacos                       1018.80
Chips                                     457.70
Chips and Fresh Tomato Salsa              297.70
Chips and Guacamole                      1968.34
Chips and Mild Fresh Tomato Salsa           3.00
Chips and Roasted Chili Corn Salsa         67.85
Chips and Roasted Chili-Corn Salsa         43.02
Chips and Tomatillo Green Chili Salsa     132.75
Chips and Tomatillo Red Chili Salsa       147.50
Chips and Tomatillo-Green Chili Salsa      78.87
Chips and Tomatillo-Red Chili Salsa        59.75
Crispy Tacos                               14.80
Izze                                       67.80
Nantucket Nectar                           98.31
Salad                                      14.80
Side of Chips                             185.90
Steak Bowl                               1920.49
Steak Burrito                            3354.34
Steak Crispy Tacos                        312.84
Steak Salad                                34.76
Steak Salad Bowl                          291.09
Steak Soft Tacos                          503.44
Veggie Bowl                               738.63
Veggie Burrito                            823.53
Veggie Crispy Tacos                         8.49
Veggie Salad                               50.94
Veggie Salad Bowl                         157.50
Veggie Soft Tacos                          67.92
dtype: float64

In [62]:
#내림차순 정렬
item_total_price.sort_values(ascending = False)

item_name
Chicken Bowl                             6232.59
Chicken Burrito                          4840.29
Steak Burrito                            3354.34
Chips and Guacamole                      1968.34
Steak Bowl                               1920.49
Chicken Salad Bowl                       1076.25
Chicken Soft Tacos                       1018.80
Veggie Burrito                            823.53
Barbacoa Burrito                          790.79
Veggie Bowl                               738.63
Carnitas Bowl                             638.29
Barbacoa Bowl                             573.54
Carnitas Burrito                          521.40
Steak Soft Tacos                          503.44
Chips                                     457.70
Canned Soft Drink                         438.75
Chicken Crispy Tacos                      424.50
Carnitas Soft Tacos                       359.60
6 Pack Soft Drink                         356.95
Steak Crispy Tacos                        312.84
Chips and Fresh Tomato Salsa              297.70
Steak Salad Bowl                          291.09
Bottled Water                             229.99
Barbacoa Soft Tacos                       224.75
Side of Chips                             185.90
Veggie Salad Bowl                         157.50
Chips and Tomatillo Red Chili Salsa       147.50
Canned Soda                               137.34
Chips and Tomatillo Green Chili Salsa     132.75
Barbacoa Crispy Tacos                     107.88
Nantucket Nectar                           98.31
Barbacoa Salad Bowl                        93.90
Chips and Tomatillo-Green Chili Salsa      78.87
Chicken Salad                              73.71
Carnitas Crispy Tacos                      71.92
Veggie Soft Tacos                          67.92
Chips and Roasted Chili Corn Salsa         67.85
Izze                                       67.80
Chips and Tomatillo-Red Chili Salsa        59.75
Carnitas Salad Bowl                        56.34
Veggie Salad                               50.94
Burrito                                    44.40
Chips and Roasted Chili-Corn Salsa         43.02
Steak Salad                                34.76
Bowl                                       29.60
Salad                                      14.80
Crispy Tacos                               14.80
Carnitas Salad                              8.99
Veggie Crispy Tacos                         8.49
Chips and Mild Fresh Tomato Salsa           3.00
dtype: float64

In [63]:
# 상위 10개만 출력하기
item_total_price.sort_values(ascending = False)[:10]

item_name
Chicken Bowl           6232.59
Chicken Burrito        4840.29
Steak Burrito          3354.34
Chips and Guacamole    1968.34
Steak Bowl             1920.49
Chicken Salad Bowl     1076.25
Chicken Soft Tacos     1018.80
Veggie Burrito          823.53
Barbacoa Burrito        790.79
Veggie Bowl             738.63
dtype: float64